<?php

function mailchecker_menu() {

  $items = array();

  $items['admin/config/mailchecker'] = array(
    'type' => MENU_CALLBACK,
    'title' =>  'Mailchecker configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailchecker_conf'),
    'access arguments' => array('access administration page')
  );

  return $items;

}

function mailchecker_conf() {
  $form = array();
  
  $form['general'] = array(
    '#title' => t('General'),
    '#type' => 'fieldset',
  );

  $form['general']['path'] = array(
    '#title' => t('Source path'),
    '#description' => t('The source path to "jquery.mailcheck.min.js".'),
    '#type' => 'textfield',
    '#default_value' => variable_get('mailchecker_path'),
  );

  $form['general']['domains'] = array(
    '#title' => t('Domains'),
    '#description' => t('If we forgot any domains, you can add them here. Seperate with a comma.'),
    '#default_value' => implode(', ', variable_get('mailchecker_domains')),
    '#type' => 'textarea',
    '#rows' => 3,
  );

  $form['general']['message'] = array(
    '#title' => t('Message'),
    '#description' => 'Change the message which meets the users. <br/>[corrected-mail] is replaced by the typo corrected mail',
    '#type' => 'textarea',
    '#rows' => 6,
    '#default_value' => variable_get('mailchecker_message'),
  );

  $form['where'] = array(
    '#title' => t('Where'),
    '#type' => 'fieldset',
  );
  
  $form['where']['register'] = array(
    '#title' => t('Check email on register form'),
    '#type' => 'checkbox',
    '#default_value' => variable_get('mailchecker_onregister'),
  );

  /****
  * This needs some investigations first, on standby.
  $form['where']['login'] = array(
    '#title' => t('Check email on login form'),
    '#description' => t('In case you use email instead of username, for login.'),
    '#type' => 'checkbox',
    '#default_value' => variable_get('mailchecker_onlogin'),
  );
  ****/

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('save'),
  );

  return $form;
}

function mailchecker_conf_submit($form, &$form_state) {

  // Simply store data.
  variable_set('mailchecker_domains', explode(',', str_replace(' ', '', $form_state['input']['domains'])));
  variable_set('mailchecker_onregister', $form_state['input']['register']);  
  //variable_set('mailchecker_onlogin', $form_state['input']['login']);  
  variable_set('mailchecker_message', $form_state['input']['message']);
  variable_set('mailchecker_show', $form_state['input']['show']);
  if(!file_exists(DRUPAL_ROOT.$form_state['input']['path'])) drupal_set_message('Source path was not found.', 'error');
  variable_set('mailchecker_path', $form_state['input']['path']);
}

function load_mailcheck() {
  // Load Files
  drupal_add_js(variable_get('mailchecker_path'));
  drupal_add_js(drupal_get_path('module', 'mailchecker') . '/js/mailchecker.js');

  // Inject settings
  $domains = variable_get('mailchecker_domains');
  $markup = variable_get('mailchecker_message');
  $settings = array('mailcheck' => array('domains' => $domains, 'message' => $markup));
  drupal_add_js($settings, 'setting');
}

function mailchecker_form_alter(&$form, &$form_state, $form_id) {

  // Check if we are on the right form, also check for settings 
  if($form_id == 'user_register_form' && variable_get('mailchecker_onregister')) {

    load_mailcheck();
    $form['account']['mail']['#attributes'] = array('class' => array('mailcheck'));
    $form['account']['mail']['#suffix'] = '<div class="mailcheck-action"></div>'; 
  }
}

function mailchecker_field_info() {
  return array(
    'mailchecker' =>  array(
      'label' => t('Mail Check'),
      'description' => t('Adds a corrector to a mail field, checking for spelling errors.'), 
      'default_widget' => 'mail_check',
    )
  );  
}

function mailchecker_field_widget_info() {
  return array(
    'mail_check' => array(
      'label' => t('Text field with mail check'),
      'field types' => array('text', 'email'),
    ),
  );
}

function mailchecker_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  
  $element[$element['#field_name']] = array(
    '#type' => 'textfield',
    '#title' => t($element['#field_name']),
    '#attributes' => array('class' => array('mailcheck')),
  );

  return $element;
}

